2024-11-23 22:11:45,078 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-11-23 22:11:45,078 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Configure stats pid to 1174346
2024-11-23 22:11:45,078 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Loading settings from /home/nlp-05/.config/wandb/settings
2024-11-23 22:11:45,079 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Loading settings from /data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/wandb/settings
2024-11-23 22:11:45,079 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-23 22:11:45,080 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': 'disabled', '_disable_service': None}
2024-11-23 22:11:45,080 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-23 22:11:45,085 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] calling init triggers
2024-11-23 22:11:45,085 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] wandb.init called with sweep_config: {}
config: {'batch_size': 2048}
2024-11-23 22:11:45,085 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] calling init triggers
2024-11-23 22:11:45,085 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] wandb.init called with sweep_config: {}
config: {'batch_size': 2048}
2024-11-23 22:11:45,085 INFO    MainThread:1174346 [wandb_init.py:_log_setup():534] Logging user logs to /data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/wandb/run-20241123_221145-gk3ufl8s/logs/debug.log
2024-11-23 22:11:45,086 INFO    MainThread:1174346 [wandb_init.py:_log_setup():535] Logging internal logs to /data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/wandb/run-20241123_221145-gk3ufl8s/logs/debug-internal.log
2024-11-23 22:11:45,086 INFO    MainThread:1174346 [wandb_init.py:init():621] calling init triggers
2024-11-23 22:11:45,087 INFO    MainThread:1174346 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {'wandb': True, 'batch_size': 2048, 'learning_rate': 0.001, 'validation_interval': 10, 'checkpoint_file_path': '/data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/checkpoints'}
2024-11-23 22:11:45,088 INFO    MainThread:1174346 [wandb_init.py:init():646] re-initializing run, found existing run on stack: b9wnh6ay
2024-11-23 22:11:45,091 INFO    MainThread:1174346 [wandb_run.py:_finish():2158] finishing run chosuyeon-korea-university-of-technology-and-education/cnn_fashion_mnist/b9wnh6ay
2024-11-23 22:11:45,093 ERROR   MainThread:1174346 [jupyter.py:save_history():451] Run pip install nbformat to save notebook history
2024-11-23 22:11:45,093 INFO    MainThread:1174346 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2024-11-23 22:11:45,093 INFO    MainThread:1174346 [wandb_init.py:_jupyter_teardown():462] cleaning up jupyter logic
2024-11-23 22:11:45,094 INFO    MainThread:1174346 [wandb_run.py:_atexit_cleanup():2426] got exitcode: 0
2024-11-23 22:11:45,095 INFO    MainThread:1174346 [wandb_run.py:_restore():2408] restore
2024-11-23 22:11:45,096 INFO    MainThread:1174346 [wandb_run.py:_restore():2414] restore done
2024-11-23 22:11:51,139 INFO    MainThread:1174346 [wandb_run.py:_footer_history_summary_info():3975] rendering history
2024-11-23 22:11:51,139 INFO    MainThread:1174346 [wandb_run.py:_footer_history_summary_info():4007] rendering summary
2024-11-23 22:11:51,156 INFO    MainThread:1174346 [wandb_run.py:_footer_sync_info():3934] logging synced files
2024-11-23 22:11:51,163 INFO    MainThread:1174346 [wandb_init.py:init():671] starting backend
2024-11-23 22:11:51,163 INFO    MainThread:1174346 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-11-23 22:11:51,175 INFO    MainThread:1174346 [backend.py:ensure_launched():188] starting backend process...
2024-11-23 22:11:51,178 INFO    MainThread:1174346 [backend.py:ensure_launched():193] started backend process with pid: 1179797
2024-11-23 22:11:51,178 INFO    MainThread:1174346 [wandb_init.py:init():688] backend started and connected
2024-11-23 22:11:51,184 INFO    MainThread:1174346 [wandb_run.py:_label_probe_notebook():1342] probe notebook
2024-11-23 22:11:51,185 INFO    MainThread:1174346 [wandb_init.py:init():783] updated telemetry
2024-11-23 22:11:51,197 INFO    MainThread:1174346 [wandb_init.py:init():816] communicating run to backend with 90.0 second timeout
2024-11-23 22:11:52,148 INFO    MainThread:1174346 [wandb_init.py:init():867] starting run threads in backend
2024-11-23 22:11:54,015 INFO    MainThread:1174346 [wandb_run.py:_console_start():2463] atexit reg
2024-11-23 22:11:54,016 INFO    MainThread:1174346 [wandb_run.py:_redirect():2311] redirect: wrap_raw
2024-11-23 22:11:54,016 INFO    MainThread:1174346 [wandb_run.py:_redirect():2376] Wrapping output streams.
2024-11-23 22:11:54,016 INFO    MainThread:1174346 [wandb_run.py:_redirect():2401] Redirects installed.
2024-11-23 22:11:54,017 INFO    MainThread:1174346 [wandb_init.py:init():911] run started, returning control to user process
2024-11-23 22:11:54,038 INFO    MainThread:1174346 [wandb_watch.py:_watch():71] Watching
2024-11-23 22:13:03,481 ERROR   MainThread:1174346 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1255, in init
    wi.setup(kwargs)
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 193, in setup
    self._wl = wandb_setup.setup(settings=setup_settings)
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 390, in setup
    ret = _setup(settings=settings)
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 330, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 306, in __init__
    _WandbSetup._instance._update(settings=settings)
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 155, in _update
    self._settings.update(settings, source=wandb_settings.Source.SETUP)
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1530, in update
    self.__dict__[key].update(settings.pop(key), source=source)
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 601, in update
    self._value = self._validate(self._preprocess(value))
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 571, in _validate
    if not v(value):
  File "/home/nlp-05/anaconda3/envs/DL/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1014, in _validate_mode
    raise UsageError(f"Settings field `mode`: {value!r} not in {choices}")
wandb.errors.errors.UsageError: Settings field `mode`: 'abled' not in {'offline', 'disabled', 'shared', 'dryrun', 'online', 'run'}
2024-11-23 22:14:04,372 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-11-23 22:14:04,372 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Configure stats pid to 1174346
2024-11-23 22:14:04,372 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Loading settings from /home/nlp-05/.config/wandb/settings
2024-11-23 22:14:04,373 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Loading settings from /data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/wandb/settings
2024-11-23 22:14:04,378 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-23 22:14:04,378 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': 'disabled', '_disable_service': None}
2024-11-23 22:14:04,378 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-23 22:14:04,379 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] calling init triggers
2024-11-23 22:14:04,379 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] wandb.init called with sweep_config: {}
config: {'batch_size': 2048}
2024-11-23 22:14:04,379 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] calling init triggers
2024-11-23 22:14:04,379 INFO    MainThread:1174346 [wandb_setup.py:_flush():79] wandb.init called with sweep_config: {}
config: {'batch_size': 2048}
2024-11-23 22:14:04,380 INFO    MainThread:1174346 [wandb_init.py:_log_setup():534] Logging user logs to /data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/wandb/run-20241123_221404-jailj2qy/logs/debug.log
2024-11-23 22:14:04,381 INFO    MainThread:1174346 [wandb_init.py:_log_setup():535] Logging internal logs to /data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/wandb/run-20241123_221404-jailj2qy/logs/debug-internal.log
2024-11-23 22:14:04,382 INFO    MainThread:1174346 [wandb_init.py:_jupyter_setup():480] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9fdc8cb220>
2024-11-23 22:14:04,382 INFO    MainThread:1174346 [wandb_init.py:init():621] calling init triggers
2024-11-23 22:14:04,382 INFO    MainThread:1174346 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {'wandb': True, 'batch_size': 2048, 'learning_rate': 0.001, 'validation_interval': 10, 'checkpoint_file_path': '/data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/checkpoints'}
2024-11-23 22:14:04,383 INFO    MainThread:1174346 [wandb_init.py:init():646] re-initializing run, found existing run on stack: gk3ufl8s
2024-11-23 22:14:04,386 INFO    MainThread:1174346 [wandb_run.py:_finish():2158] finishing run chosuyeon-korea-university-of-technology-and-education/cnn_fashion_mnist/gk3ufl8s
2024-11-23 22:14:04,387 INFO    MainThread:1174346 [wandb_run.py:_atexit_cleanup():2426] got exitcode: 0
2024-11-23 22:14:04,388 INFO    MainThread:1174346 [wandb_run.py:_restore():2408] restore
2024-11-23 22:14:04,388 INFO    MainThread:1174346 [wandb_run.py:_restore():2414] restore done
2024-11-23 22:14:10,950 INFO    MainThread:1174346 [wandb_run.py:_footer_history_summary_info():3975] rendering history
2024-11-23 22:14:10,951 INFO    MainThread:1174346 [wandb_run.py:_footer_history_summary_info():4007] rendering summary
2024-11-23 22:14:10,967 INFO    MainThread:1174346 [wandb_run.py:_footer_sync_info():3934] logging synced files
